### ISSUE TITLE
Warning: Invalid DOM property `class`. Did you mean `className`?

### ISSUE THREAD

**Issue by DavisJeremy** [whitman-books-online/whitman-books-online#101]
Warning: Invalid DOM property `class`. Did you mean `className`?
    in div (at Profile.js:39)
    in div (created by Paper)
    in Paper (at Profile.js:34)
    in div (created by Paper)
    in Paper (at Page.js:8)
    in Page (at Profile.js:33)
    in Profile (created by Connect(Profile))
    in Connect(Profile) (created by Route)
    in Route (created by withRouter(Connect(Profile)))
    in withRouter(Connect(Profile)) (at PrivateRoute.js:14)
    in Route (at PrivateRoute.js:10)
    in PrivateRoute (created by Connect(PrivateRoute))
    in Connect(PrivateRoute) (at Home.js:46)
    in Switch (at Home.js:40)
    in div (at Home.js:32)
    in Home (at App.js:65)
    in MuiThemeProvider (at App.js:64)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (at App.js:63)
    in Provider (at App.js:62)
    in App (at index.js:7)

**Comment by farmanrl** [comment]
This is because `class` is used instead of `className` for defining custom styles in our tags.
