### ISSUE TITLE
Feature Request: after typing in an ISBN, hitting enter should do the same thing as clicking the confirm button

### ISSUE THREAD

**Issue by DavisJeremy** [whitman-books-online/whitman-books-online#103]
I've noticed that when I enter an ISBN, I automatically hit the enter key which currently does nothing. Because of this intuitive action, I think it would be great if we could incorporate it.

**Comment by JulesChoq** [comment]
Can def do this, when I put it all in redux

**Comment by JulesChoq** [comment]
i think cooper did this a while back
