### ISSUE TITLE
Poster - Documentation

### ISSUE THREAD

**Issue by phillits** [whitman-books-online/whitman-books-online#118]

**Comment by phillits** [comment]
Working document: https://docs.google.com/document/d/1QWUa3HLpeoPbCV-QBXZpP5eo72Xj3KKeGGrBvVRPRHQ/edit

**Comment by dunnkv** [comment]
Hey, I do not think this should be closed yet. First off, this is not going to fit on the poster. This needs to be edited down. Secondly, this has not been added to the poster yet.

**Comment by kirklange** [comment]
Can we get an approximate word limit?
