### ISSUE TITLE
Selling Books Does Not Work

### ISSUE THREAD

**Issue by nlonberg** [whitman-books-online/whitman-books-online#165]
As of posting this issue, our master repository does not properly post books.  Pressing "Submit" to sell a book results in the successful creation of a new book object, but **the book object has no listing ID** attached to it.  This means that Feed doesn't load the book.  **Previous commits had this functionality**.  But now it does not work.

**Comment by banta-isaiah** [comment]
This was an issue with the backend not being hosted, not with frontend, we good now.
