### ISSUE TITLE
Get a github account and/or become part of the Whitman Books Online Group

### ISSUE THREAD

**Issue by banta-isaiah** [whitman-books-online/whitman-books-online#27]
The following people can check mark their name after they have completed this and then help out their neighbor with the Design Doc for the first ~20 minutes of the period.

- [x] Andrew

- [x] Cooper Lazar

- [x] Paul (aka 'Hoyt')

- [x] Isaiah S. 

- [x] Jack 

- [x] Max

- [x] Pablo 

Then check-in with either me and/or your team leaders so that we can get started on writing code.

**Comment by Izayuh** [comment]
:)

**Comment by msheffield** [comment]
:)

**Comment by harveyam** [comment]
:)

**Comment by jackstew24** [comment]
:)

**Comment by milloypr** [comment]
(:

**Comment by pablofernandezcom** [comment]
(:)
