### ISSUE TITLE
Research established ways of doing search suggestions

### ISSUE THREAD

**Issue by jessebl** [whitman-books-online/whitman-books-online#34]
Search suggestions could be provided by the back end API, or determined by the front end app based off of titles provided by the API. Please research established ways of how to provide search suggestions to the user, with a focus on how the solution gets broken down across the front end and back end.

**Comment by jessebl** [comment]
In order to close this issue, we need a breakdown of what front end and back end are each responsible for, including API calls that the back end will need to implement.

**Comment by farmanrl** [comment]
http://whitman-books-online-documentation.readthedocs.io/en/latest/meeting-notes/2018-03-27.html

**Comment by jessebl** [comment]
I think that this has been dealt with in front end in one manner or another? Closing for now.
