### ISSUE TITLE
Determine which SQLAlchemy module to use

### ISSUE THREAD

**Issue by jessebl** [whitman-books-online/whitman-books-online#4]
There has been a question of whether or not we will use the `orm` module, or maybe `flask-sqlalchemy` (iirc). The people who have the most experience and insight with these respective modules should collaborate and figure out which suits our needs best.

**Comment by OwenDavisBower** [comment]
@sean-m-miller and I discussed the possibilities and concluded that we should be able to use flask-sqlalchemy and the orm module together in order to best suit our needs. Our next step is working together to combine our sqlalchemy databases in order to achieve our desired functionality.

**Comment by jessebl** [comment]
Perfect.
