### ISSUE TITLE
Frontend app jumps to log in immediately and gives a TypeError

### ISSUE THREAD

**Issue by jessebl** [whitman-books-online/whitman-books-online#72]
Without clicking at all, the site gives `TypeError: profileObj is undefined`.

Here are screenshots of the error:
![Source trace](https://i.imgur.com/LWxvMsR.png)
![Compiled trace](https://i.imgur.com/r7M8WNT.png)

**Comment by farmanrl** [comment]
Newest pull request might fix this issue - give it a shot and let me know.

**Comment by jessebl** [comment]
This changes stuff! Now I remain at the root of the app (<ip address>:3000/), and after a moment ["Invalid Login"](https://i.imgur.com/UEiJoiz.png) is displayed.

Then, once I click on the login button, a window (presumably for Oauth2) pops up and displays a 400 error.

**Comment by farmanrl** [comment]
This has to do with our whitelisted addresses, we'll need to add our hosted addresses if we want it to work
