### ISSUE TITLE
Whitman Books Online Logo Creation

### ISSUE THREAD

**Issue by banta-isaiah** [whitman-books-online/whitman-books-online#8]
We need a logo created. Preferably a PNG file.

**Comment by jessebl** [comment]
Or an SVG, at least to have in the repo for PNG generation down the line.

**Comment by JulesChoq** [comment]
Playing around will do other stuff too
![png version](https://user-images.githubusercontent.com/17147348/38290607-ed6f02e4-3790-11e8-9d6f-4929d695a7b6.png)

**Comment by JulesChoq** [comment]
![wbo logo 2](https://user-images.githubusercontent.com/17147348/38291133-2bb76e90-3793-11e8-93bc-4070109fad56.png)

**Comment by JulesChoq** [comment]
![whitmanlogo3](https://user-images.githubusercontent.com/17147348/38291882-7eb53ef8-3796-11e8-89be-6c97fdb662ae.png)

**Comment by nlonberg** [comment]
![full logo](https://user-images.githubusercontent.com/23039888/38327192-7d73fa82-37fc-11e8-899b-d8a1bd141600.png)
![short logo](https://user-images.githubusercontent.com/23039888/38327193-7d8ac17c-37fc-11e8-94ff-69a947486fd7.png)

**Comment by dunnkv** [comment]
![wbonline](https://user-images.githubusercontent.com/37000847/39200902-48db3500-47a2-11e8-83f7-e10aa6f233b6.png)


The official logo has been updated for large format and has been put on the poster

**Comment by dunnkv** [comment]
![wbonlineblack](https://user-images.githubusercontent.com/37000847/39201006-9a095f24-47a2-11e8-8c02-91cb76162228.png)

Here is the updated and high res version of the logo let me know if we want to change anything, currently would be on the binder and the poster

**Comment by jessebl** [comment]
I like the look, personally. Could we get an SVG of it in the repo for reproducibility?

**Comment by banta-isaiah** [comment]
Done! It is under: docs/images/wbo_logo.svg

Thanks everyone for contributing.
